runtime: python311
entrypoint: gunicorn -b :$PORT run:app --workers=4 --threads=4

handlers:
- url: /static
  static_dir: static
  expiration: "30d"

- url: /.*
  script: auto

env_variables:
  # The actual Gemini API key should be added via the GCP App Engine 
  # dashboard environment variables for security.
  GEMINI_API_KEY: "PLACEHOLDER"
